# Generated by Django 5.2.4 on 2025-10-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('time_ms', models.IntegerField()),
                ('rounds', models.IntegerField()),
            ],
        ),
    ]
